openapi: 3.0.3
info:
  title: WASAphoto
  description: |-
    Versione 1 del progetto WASA.
  version: "1"
tags:
  - name: doLogin
    description: Login and user authentication
  - name: setMyUsername
    description: Set and change username
  - name: uploadPhoto
    description: Upload photos
  - name: deletePhoto
    description: Delete photos
  - name: followUser
    description: Follow users
  - name: unfollowUser
    description: Unfollow users
  - name: banUser
    description: Ban users
  - name: unbanUser
    description: Unban users
  - name: likePhoto
    description: Like photos
  - name: unlikePhoto
    description: Unlike photos
  - name: commentPhoto
    description: Comment on photos
  - name: uncommentPhoto
    description: Delete comments
  - name: getUserProfile
    description: Get user profile
  - name: getMyStream
    description: Get user stream
components:
  schemas:
    Username:
      type: object
      properties:
        username:
          type: string
    User:
      type: object
      properties:
        userID:
          type: integer
        username:
          type: string
    Photo:
      type: object
      properties:
        photoID:
          type: integer
        user:
          $ref: '#/components/schemas/User'
        URL:
          type: string
        imageData:
          type: string
          format: byte
        caption:
          type: string
        nlike:
          type: integer
        ncomment:
          type: integer
        liked:
          type: boolean
        createdAt:
          type: string
          format: date-time
    Comment:
      type: object
      properties:
        commentID:
          type: integer
        ownerID:
          type: integer
        photoID:
          type: integer
        user:
          $ref: '#/components/schemas/User'
        lyric:
          type: string
        createdAt:
          type: string
          format: date-time
    Profile:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        name:
          type: string
        follower:
          type: integer
        following:
          type: integer
        postsCount:
          type: integer
        isFollowed:
          type: boolean
    Authorization:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        token:
          type: integer
  responses:
    # 200 response
    Success:
      description: Success
      content:
        text/plain:
          schema:
            description: Success message
            type: string
            properties:
              message:
                type: string
    # 201 response
    Created:
      description: Created
    # 204 response
    NoContent:
      description: No content
    # 400 response
    BadRequest:
      description: Bad request
    # 401 response
    Unauthorized:
      description: Unauthorized
    # 403 response
    Forbidden:
      description: Forbidden
    # 404 response
    NotFound:
      description: Not found
    # 500 response
    InternalServerError:
      description: Internal server error
    

paths:
  /login:
    post:
      summary: User login
      tags:
        - doLogin
      operationId: doLogin
      requestBody:
        description: User credentials
        content:
          application/json:
            schema:
              description: username of the user
              type: object
              properties:
                username: { $ref: '#/components/schemas/Username' }
        required: true
      responses:
        '200': { $ref: '#/components/responses/Success' }
        "201": { $ref: '#/components/responses/Created' }
        "400": { $ref: '#/components/responses/BadRequest' }
        "500": { $ref: '#/components/responses/InternalServerError' }

  /profiles/{profileUserID}:
    get:
      summary: Get user profile
      tags:
        - User Profile
      responses:
        '200':
          description: User profile retrieved
    delete:
      summary: Delete user
      tags:
        - User Profile
      responses:
        '204':
          description: User deleted

  /profiles/{profileUserID}/username:
    put:
      summary: Change username
      tags:
        - User Profile
      responses:
        '200':
          description: Username updated

  /profiles/{profileUserID}/profile-picture:
    put:
      summary: Change profile picture
      tags:
        - User Profile
      responses:
        '200':
          description: Profile picture updated

  /profiles/{profileUserID}/reset-profile-picture:
    put:
      summary: Reset profile picture
      tags:
        - User Profile
      responses:
        '200':
          description: Profile picture reset

  /profiles/{profileUserID}/followings/{targetUserID}:
    put:
      summary: Follow a user
      tags:
        - Social
      responses:
        '200':
          description: User followed
    delete:
      summary: Unfollow a user
      tags:
        - Social
      responses:
        '200':
          description: User unfollowed

  /profiles/{profileUserID}/followings:
    get:
      summary: Get followings
      tags:
        - Social
      responses:
        '200':
          description: List of followings retrieved

  /profiles/{profileUserID}/followers:
    get:
      summary: Get followers
      tags:
        - Social
      responses:
        '200':
          description: List of followers retrieved

  /profiles/{profileUserID}/bans/{targetUserID}:
    put:
      summary: Ban a user
      tags:
        - Social
      responses:
        '200':
          description: User banned
    delete:
      summary: Unban a user
      tags:
        - Social
      responses:
        '200':
          description: User unbanned

  /profiles/{profileUserID}/bans:
    get:
      summary: Get banned users
      tags:
        - Social
      responses:
        '200':
          description: List of banned users retrieved

  /profiles/{profileUserID}/posts:
    post:
      summary: Upload a post
      tags:
        - Posts
      responses:
        '201':
          description: Post uploaded
    get:
      summary: Get user posts
      tags:
        - Posts
      responses:
        '200':
          description: List of posts retrieved

  /profiles/{profileUserID}/posts/{postID}/caption:
    put:
      summary: Change post caption
      tags:
        - Posts
      responses:
        '200':
          description: Caption updated

  /profiles/{profileUserID}/posts/{postID}:
    delete:
      summary: Delete a post
      tags:
        - Posts
      responses:
        '204':
          description: Post deleted

  /profiles/{profileUserID}/posts/{postID}/likes/{userID}:
    put:
      summary: Like a post
      tags:
        - Posts
      responses:
        '200':
          description: Post liked
    delete:
      summary: Unlike a post
      tags:
        - Posts
      responses:
        '200':
          description: Post unliked

  /profiles/{profileUserID}/posts/{postID}/likes:
    get:
      summary: Get likes of a post
      tags:
        - Posts
      responses:
        '200':
          description: List of likes retrieved

  /profiles/{profileUserID}/posts/{postID}/comments:
    post:
      summary: Comment on a post
      tags:
        - Posts
      responses:
        '201':
          description: Comment added
    get:
      summary: Get comments on a post
      tags:
        - Posts
      responses:
        '200':
          description: List of comments retrieved

  /profiles/{profileUserID}/posts/{postID}/comments/{commentID}:
    delete:
      summary: Delete a comment
      tags:
        - Posts
      responses:
        '204':
          description: Comment deleted

  /profiles/{profileUserID}/feed:
    get:
      summary: Get user feed
      tags:
        - Posts
      responses:
        '200':
          description: Feed retrieved

  /profiles:
    get:
      summary: Search users
      tags:
        - User Profile
      responses:
        '200':
          description: Search results retrieved

  /liveness:
    get:
      summary: Check API liveness
      tags:
        - Misc
      responses:
        '200':
          description: API is live
